/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sietemediablackjack;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author Dani
 */
public class Ventana extends javax.swing.JFrame {

    private GestoraDeBarajas gestora;
    private Partida laPartidaActual;
    private String nombre;
    private float puntuacion = 0;
    private float puntuacionBanca = 0;
    private float valorBanca = 0;
    private int jugadasSeguidas = 0;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        
        nombre = JOptionPane.showInputDialog("Nombre del jugador:");
        initComponents();
        bNuevaPartida.setEnabled(false);
        bPideCarta.setEnabled(false);
        bPlantarse.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboBaraja = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taResultado = new javax.swing.JTextArea();
        bPideCarta = new javax.swing.JButton();
        bPlantarse = new javax.swing.JButton();
        bNuevaPartida = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jpCartasBanca = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jpCartasJugador = new javax.swing.JPanel();
        jlPuntuacion = new javax.swing.JLabel();
        jlPuntuacionBanca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elige Baraja");

        comboBaraja.setModel(new DefaultComboBoxModel(TiposDeBaraja.nombresBarajas()));
        comboBaraja.setSelectedItem(null);
        comboBaraja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBarajaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        taResultado.setEditable(false);
        taResultado.setColumns(20);
        taResultado.setRows(5);
        jScrollPane1.setViewportView(taResultado);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );

        bPideCarta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sietemediablackjack/images/pedircarta.png"))); // NOI18N
        bPideCarta.setText("Pedir Carta");
        bPideCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPideCartaActionPerformed(evt);
            }
        });

        bPlantarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sietemediablackjack/images/stop.png"))); // NOI18N
        bPlantarse.setText("Plantarse");
        bPlantarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlantarseActionPerformed(evt);
            }
        });

        bNuevaPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sietemediablackjack/images/otra_partida.png"))); // NOI18N
        bNuevaPartida.setText("Nueva Partida");
        bNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevaPartidaActionPerformed(evt);
            }
        });

        jpCartasBanca.setBackground(new java.awt.Color(0, 153, 51));
        jpCartasBanca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BANCA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane3.setViewportView(jpCartasBanca);

        jpCartasJugador.setBackground(new java.awt.Color(0, 153, 51));
        jpCartasJugador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "JUGADOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane2.setViewportView(jpCartasJugador);

        jlPuntuacion.setForeground(new java.awt.Color(255, 255, 255));

        jlPuntuacionBanca.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(comboBaraja, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 427, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlPuntuacionBanca)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlPuntuacion)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bPideCarta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bPlantarse)
                                        .addGap(25, 25, 25))))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bNuevaPartida)
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBaraja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bPideCarta)
                            .addComponent(bPlantarse))
                        .addGap(18, 18, 18)
                        .addComponent(bNuevaPartida)
                        .addGap(85, 85, 85)
                        .addComponent(jlPuntuacion)
                        .addGap(18, 18, 18)
                        .addComponent(jlPuntuacionBanca)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bPideCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPideCartaActionPerformed
        // TODO add your handling code here:
        Carta nuevaCarta = laPartidaActual.obtenerOtraCarta(gestora);
        laPartidaActual.jugador.add(nuevaCarta);
        JLabel etiqueta = new JLabel();
        jpCartasJugador.add(etiqueta);
        ImageIcon imagenCarta = new ImageIcon(getClass().getResource("/sietemediablackjack/" + nuevaCarta.getImagen()));
        etiqueta.setIcon(imagenCarta);
        puntuacion += nuevaCarta.getValor();
        jlPuntuacion.setText("Jugador: " + String.valueOf(puntuacion) + " puntos.");
        jugadasSeguidas++;
        bPlantarse.setEnabled(true);
        if(laPartidaActual.jugador.devuelveSumaCartas() == 21.0f && jugadasSeguidas == 2){
            blackJack(laPartidaActual.jugador);
        }
        if(laPartidaActual.jugador.devuelveSumaCartas() > laPartidaActual.getLimite()){
            mPlantarse();
        }
    }//GEN-LAST:event_bPideCartaActionPerformed

    private void mPlantarse(){
        jugadasSeguidas = 0;
        JOptionPane.showMessageDialog(this, "Es el turno de la banca.");
        bNuevaPartida.setEnabled(true);
        bPideCarta.setEnabled(false);
        bPlantarse.setEnabled(false);
        mGenerarCartasBanca();
    }
    
    private void mGenerarCartasBanca(){
        while(laPartidaActual.banca.devuelveSumaCartas() <= valorBanca){
            JOptionPane.showMessageDialog(this, "La banca pide una carta.");
            Carta nuevaCarta = laPartidaActual.obtenerOtraCarta(gestora);
            laPartidaActual.banca.add(nuevaCarta);
            JLabel etiqueta = new JLabel();
            jpCartasBanca.add(etiqueta);
            ImageIcon imagenCarta = new ImageIcon(getClass().getResource("/sietemediablackjack/" + nuevaCarta.getImagen()));
            etiqueta.setIcon(imagenCarta);
            puntuacionBanca += nuevaCarta.getValor();
            jlPuntuacionBanca.setText("Banca: " + String.valueOf(puntuacionBanca) + " puntos.");
            jugadasSeguidas++;
            if(laPartidaActual.banca.devuelveSumaCartas() > laPartidaActual.getLimite()){
                break;
            }
        }
        if(laPartidaActual.banca.devuelveSumaCartas() == 21 && jugadasSeguidas == 2){
                blackJack(laPartidaActual.banca);
        } else {
            JOptionPane.showMessageDialog(this, "La banca se planta.");
            darResultados();   
        }
    }
    
    private void comboBarajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBarajaActionPerformed
        // TODO add your handling code here:
        mNuevaPartida();
    }//GEN-LAST:event_comboBarajaActionPerformed

    private void bNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevaPartidaActionPerformed
        // TODO add your handling code here:
        mNuevaPartida();
    }//GEN-LAST:event_bNuevaPartidaActionPerformed

    private void bPlantarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlantarseActionPerformed
        // TODO add your handling code here:
        mPlantarse();
    }//GEN-LAST:event_bPlantarseActionPerformed

    private void darResultados(){
        taResultado.setText("Ha ganado: " + laPartidaActual.devuelveGanador());
    }
    
    private void blackJack(Jugador j){
        taResultado.setText("Se ha producido un Blackjack,\n el ganador es: " + j.getNombre());
        bNuevaPartida.setEnabled(true);
        bPideCarta.setEnabled(false);
        bPlantarse.setEnabled(false);
    }
    
    public void mNuevaPartida(){
        jugadasSeguidas = 0;
        puntuacionBanca = 0;
        puntuacion = 0;
        jlPuntuacion.setText(null);
        jlPuntuacionBanca.setText(null);
        TiposDeBaraja barajaSeleccionada = TiposDeBaraja.devuelveBaraja((String) comboBaraja.getSelectedItem());
        if(barajaSeleccionada.getNombre().equals(TiposDeBaraja.BARAJA1.getNombre())){
            this.setTitle(TiposDeBaraja.BARAJA1.getNombre());
            laPartidaActual = new Partida(new Jugador(nombre), new Jugador("Banca"), TiposDeBaraja.BARAJA1);
            valorBanca = 5.0f;
        } else if(barajaSeleccionada.getNombre().equals(TiposDeBaraja.BARAJA2.getNombre())){
            this.setTitle(TiposDeBaraja.BARAJA2.getNombre());
            laPartidaActual = new Partida(new JugadorBlackJack(nombre), new JugadorBlackJack("Banca"), TiposDeBaraja.BARAJA2);
            valorBanca = 16.0f;
        }
        this.setTitle(nombre + " " + barajaSeleccionada.getNombre());
        bNuevaPartida.setEnabled(false);
        bPideCarta.setEnabled(true);
        bPlantarse.setEnabled(false);
        
        jpCartasBanca.removeAll();
        jpCartasJugador.removeAll();
        jpCartasBanca.repaint();
        jpCartasJugador.repaint();
        taResultado.setText("");
        gestora = new GestoraDeBarajas(barajaSeleccionada);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bNuevaPartida;
    private javax.swing.JButton bPideCarta;
    private javax.swing.JButton bPlantarse;
    private javax.swing.JComboBox<String> comboBaraja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlPuntuacion;
    private javax.swing.JLabel jlPuntuacionBanca;
    private javax.swing.JPanel jpCartasBanca;
    private javax.swing.JPanel jpCartasJugador;
    private javax.swing.JTextArea taResultado;
    // End of variables declaration//GEN-END:variables
}
